pages:
  stage: deploy
  image: ruby:2.1
  script:
  - gem install bundler
  - bundle install
  - jekyll build -d public
  - cp -r _site/.well-known public
  artifacts:
    paths:
    - public
  only:
  - master
