pages:
  stage: deploy
  image: ruby:2.1
  script:
  - gem install jekyll
  - gem install redcarpet
  - gem install i18n
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master