# Site wide configuration

title: Felipe Cabargas
locale: en_US
description: Ruby Lover & Pixel Jedi.
logo: logo.png
search: true
url: http://blog.cabargas.com
production_url : http://blog.cabargas.com

# Jekyll configuration

permalink:   /:year/:month/:title
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Felipe Cabargas
  avatar: image-me.jpg
  email: felipe@cabargas.com
  disqus-shortname:
  twitter: juanpintoduran
  facebook: fcabargas
  github: felipecabargas
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: cabargas
  instagram: juanpintoduran
  flickr: pipecabargas
  tumblr: #username
  google:
    plus: #username
    analytics: 'UA-5897138-2'
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
