# Site wide configuration
title: Felipe Cabargas's NDD
baseurl: ""
url: "https://blog.nondrivendevelopment.com"
favicon: "images/ndd-logo.png"
g_analytics: UA-5897138-2

# Bio
header: Felipe Cabargas's NDD
desc: >
  A journey of missing semicolons.

# Jekyll configuration
theme: louie

permalink:   /:year/:month/:title
date_format: "%m/%d/%Y"
prev-next: true

markdown:    kramdown
highlighter: rouge

# include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
